### ISSUE TITLE
`vip dev-env update` does not consider media redirect values set in `vip-dev-env.yml`

### ISSUE THREAD

**Issue by moraleida** [Automattic/vip#2417]
Steps to reproduce:

1. Create a new site with an override file in `.wpvip`. The override file should contain a `media-redirect-domain` instruction.
    e.g:
```yml
configuration-version: 1
media-redirect-domain: 'media.example.com'
domain: 'example.com'
slug: 'wptest'
php: 8.2
```
3. change some other value in the override file and run `vip dev-env update`

**Expected result:** only mandatory values that are not set up in `vip-dev-env.yml` are prompted for.

**Actual result:** a prompt for `URL to redirect for missing media files` is always shown.

```shell
$ vip dev-env update
Using environment wptest from /Users/moraleida/dev/wptest/.wpvip/vip-dev-env.yml

? URL to redirect for missing media files ("n" to disable)? › https://media.example.com
```
